[package]
authors = ["Matt Jones <jonesmr@gmail.com>"]
description = "Library for serializing Google protobuf objects as JSON using Rust."
repository = "https://github.com/mrjones/rust-protobuf-json"
license = "MIT"
name = "protobuf-json"
version = "0.1.0"

[dependencies]
protobuf = "*"
serde_json = "*"
